### ISSUE TITLE
Adaptation for ts-259 pro

### ISSUE THREAD

**Issue by secteur0** [tomtastic/qnap-gpio#1]
Hi,
is it possible to adapt your module for a qnap ts-259 pro ? where to start ?
Because I would like to see the activity of the hard drives on the LEDs.
thanks a lot.

**Comment by tomtastic** [comment]
Not sure where you would start as I'm not familiar with the hardware, I'm guessing it doesn't contain the IT87 chip ?
Maybe try asking in the QNAP forum : https://forum.qnap.com/viewforum.php?f=191

**Comment by tomtastic** [comment]
closed
